// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joxlryifuicuecqrsbgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveGxyeWlmdWljdWVjcXJzYmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDY1MTIsImV4cCI6MjA2OTA4MjUxMn0.l6ZaIgPFznsmgpPVihlTGusFxDl1BlNu31cZmQkPe_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});